spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ae4d0ebcc3d780057648
            client-secret: d19e27a77bd1223364c85d97629700394c1656c4
            scope:
            - user:read:user
            - gist