# This is a basic workflow to help you get started with Actions

name: jacoco

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v1 
        with: 
          java-version: 1.11
          
      - name: Build with maven
        run: mvn -B test
        
      - name: Generate jacoco badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.0.1
        
      - name: Log coverage percentage
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'introvertkernel'
            git config --global user.email 'gurunathab@gmail.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi
        
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/
